<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <SourceRevisionId>build$([System.DateTime]::UtcNow.ToString("ddMMyyyyHHmmss"))</SourceRevisionId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NakamaClient" Version="3.21.2" />
    <PackageReference Include="Sprache" Version="2.3.1" />
    <PackageReference Include="Wasmtime" Version="44.0.0" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>
</Project>